defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope: 
      path: "static/img/"
      values:
        image: true

exclude:
  - "*.config.js"
  - "package*.json"
  - "assets"
  - "node_modules"